=== ChromeDevTools/devtools-frontend/scripts/json_validator/module.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "extensions": {
            "type": "array",
            "description": "Extension points",
            "items": {
                "properties": {
                    "type": {"type": "string"},
                    "order": {"type": "number"}
                }
            }
        },
        "dependencies": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "scripts": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "resources": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "skip_compilation": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "experiment": {
            "type": "string"
        }
    },
    "definitions": {
    }
}

=== ChromeDevTools/devtools-frontend/front_end/mobile_throttling/module.json
{
    "extensions": [
        {
            "type": "setting",
            "settingName": "customNetworkConditions",
            "settingType": "array",
            "defaultValue": []
        },
        {
            "type": "@UI.ActionDelegate",
            "actionId": "network-conditions.network-offline",
            "category": "Network",
            "title": "Go offline",
            "className": "MobileThrottling.ThrottlingManager.ActionDelegate",
            "tags": "device"
        },
        {
            "type": "@UI.ActionDelegate",
            "actionId": "network-conditions.network-online",
            "category": "Network",
            "title": "Go online",
            "className": "MobileThrottling.ThrottlingManager.ActionDelegate",
            "tags": "device"
        },
        {
            "type": "view",
            "location": "settings-view",
            "id": "throttling-conditions",
            "title": "Throttling",
            "order": 35,
            "className": "MobileThrottling.ThrottlingSettingsTab",
            "settings": [
                "customNetworkConditions"
            ]
        }
    ],
    "dependencies": [
        "common",
        "sdk",
        "ui",
        "protocol"
    ],
    "scripts": [
        "ThrottlingPresets.js",
        "MobileThrottlingSelector.js",
        "NetworkThrottlingSelector.js",
        "ThrottlingSettingsTab.js",
        "ThrottlingManager.js"
    ],
    "resources": [
        "throttlingSettingsTab.css"
    ]
}

=== ChromeDevTools/devtools-frontend/front_end/lighthouse_worker/module.json
{
    "dependencies": [
        "worker_service"
    ],
    "extensions": [
        {
            "type": "@Service",
            "factoryName": "LighthouseService",
            "name": "LighthouseService"
        }
    ],
    "scripts": [
        "../third_party/lighthouse/lighthouse-dt-bundle.js",
        "LighthouseService.js"
    ],
    "skip_compilation": [
        "../third_party/lighthouse/lighthouse-dt-bundle.js"
    ]
}

=== ChromeDevTools/devtools-frontend/front_end/sdk/module.json
{
    "dependencies": [
        "common",
        "host",
        "platform"
    ],
    "extensions": [
        {
            "type": "setting",
            "settingName": "skipStackFramesPattern",
            "settingType": "regex",
            "defaultValue": ""
        },
        {
            "type": "setting",
            "settingName": "skipContentScripts",
            "settingType": "boolean",
            "defaultValue": false
        },
        {
            "type": "setting",
            "settingName": "pauseOnExceptionEnabled",
            "settingType": "boolean",
            "defaultValue": false
        },
        {
            "type": "setting",
            "settingName": "pauseOnCaughtException",
            "settingType": "boolean",
            "defaultValue": false
        },
        {
            "type": "setting",
            "settingName": "enableAsyncStackTraces",
            "settingType": "boolean",
            "defaultValue": false
        }
    ],
    "scripts": [
        "InspectorBackend.js",
        "../InspectorBackendCommands.js",
        "Target.js",
        "AnimationModel.js",
        "ApplicationCacheModel.js",
        "ConsoleModel.js",
        "ContentProviders.js",
        "CookieParser.js",
        "CPUProfileDataModel.js",
        "CPUProfilerModel.js",
        "CSSMetadata.js",
        "CSSParser.js",
        "CSSStyleModel.js",
        "DOMModel.js",
        "DebuggerModel.js",
        "HAREntry.js",
        "LayerTreeModel.js",
        "NetworkLog.js",
        "OverridesSupport.js",
        "ServiceWorkerManager.js",
        "TracingManager.js",
        "TracingModel.js",
        "WorkerManager.js",
        "RuntimeModel.js",
        "Script.js",
        "ServiceWorkerCacheModel.js",
        "RemoteObject.js",
        "Resource.js",
        "ResourceTreeModel.js",
        "SourceMap.js",
        "NetworkManager.js",
        "NetworkRequest.js",
        "PaintProfiler.js",
        "HeapProfilerModel.js",
        "../SupportedCSSProperties.js"
    ],
    "skip_compilation": [
        "../InspectorBackendCommands.js",
        "../SupportedCSSProperties.js"
    ]
}
